# Generated by Django 5.0.7 on 2024-08-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailhistory',
            name='task_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mail_images/')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='useradmin.mailhistory')),
            ],
        ),
    ]
